for key,value in pairs({
    termguicolors = true,
    title = true,
    ruler = false,
    number = true,
    relativenumber = true,
    numberwidth = 2,
    cmdheight = 1,
    clipboard = "unnamedplus",
    signcolumn = "yes:3",
    lazyredraw = true,
    showmode = false,
    cursorline = true,
    showtabline = 2,
    laststatus = 3,
    sessionoptions = vim.opt.sessionoptions:append("localoptions"),
    conceallevel = 2,
    smartindent = true,
    expandtab = true,
    preserveindent = true,
    copyindent = true,
    shiftwidth = 4,
    tabstop = 4,
    softtabstop = 4,
    scrolloff = 8,
    sidescrolloff = 8,
    wrap = false,
    foldlevel = 99,
    foldlevelstart = 99,
    ignorecase = true,
    smartcase = true,
    backup = false,
    guifont = "Iosevka Nerd Font:h13", --  "Hack:h9.3",  "Iosevka Nerd Font:h9.8",  "Iosevka Nerd Font:h9.7",  "Source Code Pro:h9.5"

    -- splitbelow = true,
    -- splitright = true,
    -- undofile = true
    -- undodir = vim.fn.stdpath("cache") .. "/undodir"
    -- mouse = "a",
    -- mousefocus = true,
    -- spell = true,
    -- spelllang = en_us,
    -- foldexpr = "nvim_treesitter#foldexpr()",
    --formatexpr = "nvim_treesitter#foldexpr()",
    -- fillchars = {
    --     foldopen = "",
    --     foldclose = "",
    --     fold = "",
    --     foldsep = "",
    --     diff = "╱",
    --     eob = "",
    -- },
}) do
    vim.opt[key] = value
end
