return {
    vim = "",
    nvim = "",

    ActiveLSP = "",
    ActiveTS = "",
    ArrowLeft = "",
    ArrowRight = "",

    Bookmarks = "",
    BufferClose = "󰅖",
    DapBreakpoint = "",
    DapBreakpointCondition = "",
    DapBreakpointRejected = "",
    DapLogPoint = ".>",
    DapStopped = "󰁕",
    Debugger = "",
    DefaultFile = "󰈙",

    Diagnostic = "󰒡",
    DiagnosticWarn = "",
    DiagnosticError = "",
    DiagnosticErrorAlt = "",
    DiagnosticErrorAlt2 = "󰅚",
    DiagnosticHint = "󰌵", --  ⚑
    DiagnosticHintAlt = "",
    DiagnosticInfo = "󰋼", --  ℹ 󰙎 
    DiagnosticInfoAlt = "",

    Ellipsis = "…",
    FileNew = "",
    FileModified = "",
    FileReadOnly = "",
    FoldOpened = "",
    FoldClosed = "",
    FoldSeparator = " ",
    FolderOpen = "", -- 
    FolderClosed = "", -- 
    FolderEmpty = "",

    Git = "󰊢",
    GitRepo = "",
    GitBranch = "",
    GitConflict = "",
    GitAdd = "", --  
    GitChange = "", -- 
    GitDelete = "", -- 
    GitIgnored = "◌", -- 
    GitRenamed = "➜", -- 
    GitStaged = "✓", -- 
    GitUnstaged = "✗", -- 󰄱
    GitUntracked = "", -- ★
    GitSign = "▎",

    LSPLoaded = "",
    LSPLoading1 = "",
    LSPLoading2 = "󰀚",
    LSPLoading3 = "",
    MacroRecording = "",
    Package = "󰏖",
    Paste = "󰅌",
    Refresh = "",
    Search = "",
    Selected = "❯",
    Session = "󱂬",
    Sort = "󰒺",
    Spellcheck = "󰓆",
    Tab = "󰓩",
    TabClose = "󰅙",
    Terminal = "",
    Window = "",
    WordFile = "󰈭",

    question = '',
    clock = '',
    shaded_lock = '',
    circle = '',
    project = '',
    dashboard = '',
    history = '󰄉',
    comment = '󰅺',
    robot = '󰚩',
    lightbulb = '󰌵',
    search = '󰍉',
    code = '',
    telescope = '',
    gear = '',
    package = '',
    list = '',
    sign_in = '',
    check = '󰄬',
    fire = '',
    note = '󰎞',
    bookmark = '',
    pencil = '', -- '󰏫',
    tools = '',
    arrow_right = '',
    caret_right = '',
    chevron_right = '',
    double_chevron_right = '»',
    table = '',
    calendar = '',
}
